### ISSUE TITLE
Incompatibility with PHP8.1

### ISSUE THREAD

**Issue by proorlov** [intarocrm/rest-api-client#136]
PHP Parse error:  syntax error, unexpected token "readonly" in .../vendor/retailcrm/api-client-php/src/Component/Serializer/Parser/JMSParser.php on line 333

**Comment by Neur0toxine** [comment]
We use liip/serializer to perform serialization and deserialization of DTO. That library is using liip/metadata-parser to parse DTO annotations. liip/metadata-parser does not support PHP 8.1 yet.

We will add support for PHP 8.1 when it'll be implemented in the liip/metadata-parser.
