### ISSUE TITLE
Фильтр пользователей

### ISSUE THREAD

**Issue by AlexSuvorovKirov** [intarocrm/rest-api-client#157]
Доброго дня! Вопрос ради интереса, почему в фильтре по пользователям нет возможности делать выборку по номеру телефона? 

Спасибо за ответ!

**Comment by Neur0toxine** [comment]
Добрый день. Используйте поле `name` для поиска по номеру телефона - это поле позволяет фильтровать как по ФИО, так и по номеру.

**Comment by AlexSuvorovKirov** [comment]
Оу, неочевидно - но здорово, что такая возможность есть. Спасибо еще раз )
