### ISSUE TITLE
Проблема с files upload

### ISSUE THREAD

**Issue by mindonline** [intarocrm/rest-api-client#172]
Добрый день, возникла проблема с загрузкой файла.

Версия библиотеки:
"retailcrm/api-client-php": "~6.0"

Код:
```
$fileData = $client->getStreamFactory()->createStream("TEST");
$response = $client->files->upload(new FilesUploadRequest($fileData));
$download = $client->files->download($response->file->id);
```

Ожидаю что `$download->data->getContents()` будет равен **TEST**,
но в реальности, метод возвращает **file=TEST**
так же и для бинарных файлов возвращает всегда file=...содержимое  бинарника...
 
В CRM при попытке скачать файл тоже добавляется **file=** в начало.

**Comment by mindonline** [comment]
На первый взгляд, библиотека пытается передать файл в поле file тела запроса, но апи все тело подразумевает как файл

**Comment by AndreyMuriy** [comment]
Исправлено в v6.12.4
