### ISSUE TITLE
Нет поддержки метода /api/v5/loyalty/account/{id}/bonus/charge

### ISSUE THREAD

**Issue by itspartaru** [intarocrm/rest-api-client#206]
Не нашел в API поддержки метода /api/v5/loyalty/account/{id}/bonus/charge для списания бонусов

Есть только /api/v5/loyalty/account/{id}/bonus/credit для начисления

Также не вижу как можно самостоятельно вызвать sendRequest с указанием нужного url и параметров (только если наследовать свой класс)

**Comment by Neur0toxine** [comment]
> Не нашел в API поддержки метода `/api/v5/loyalty/account/{id}/bonus/charge` для списания бонусов

Сегодня будет релиз, в котором добавлена поддержка.

> Также не вижу как можно самостоятельно вызвать sendRequest с указанием нужного url и параметров (только если наследовать свой класс)

В API-клиенте предусмотрена возможность использования кастомных API-методов ([документация](https://github.com/retailcrm/api-client-php/blob/master/doc/customization/implementing_custom_api_methods.md)). Это может помочь если поддержку метода в клиент еще не добавили, а вызывать его нужно уже сейчас.
